//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public decimal reviewId { get; set; }
        public decimal songId { get; set; }
        public decimal rating { get; set; }
        public string review1 { get; set; }
    }
}
